### ISSUE TITLE
backend_password error under contao 3.4

### ISSUE THREAD

**Issue by markocupic** [markocupic/backend_password#2]
Hoi Andi
Folgender Fehler tritt auf, wenn ein Backend User nach der Eingabe seiner credentials beim ersten Login sein Passwort ändern muss. 
Fatal error: Call to protected Contao\Backend::__construct() from invalid context in /home/httpd/vhosts/kletterkader.com/httpdocs/contao/password.php on line 21

Liebe Grüsse
Marko

**Comment by markocupic** [comment]
Hoi Andi
Habe herausgefunden, dass deine Klasse "BackendPassword" (modules/backend_password/classes/BackendPassword.php) mit der Contao eigenen Klasse BackendPassword kolidiert. Nach Umbenennen der Klasse, des Dateinamens und natürlich der Änderung des Eintrags in der autoload.php des Moduls läuft die Erweiterung auch unter contao 3.4 wieder einwandfrei.

Liebe Grüsse
Marko

**Comment by aschempp** [comment]
siehe auch #1

Wir pflegen das Modul aktuell nicht aktiv, da wir es selber nirgends benutzen (siehe https://www.terminal42.ch/de/open-source.html). Möchtest du das Modul von uns übernehmen und weiterführen?

**Comment by markocupic** [comment]
Hoi Andi
Ja, das könnte ich schon tun. 
Verstehe dich sehr gut. Bei mir ist PHP Hobby und nicht Beruf, ich verdiene meine Brötchen andersweitig.
Liebe Grüsse
Marko

**Comment by aschempp** [comment]
Damit hast du aber meine Frage nicht beantwortet? :D

**Comment by markocupic** [comment]
Hoi Andi
Der erste Satz hätte die Antwort sein sollen. --> "Ja, das könnte ich schon tun."
Was soviel heisst wie, dass ich das Modul von dir übernehmen würde, wenn du das willst.
E liebe Gruess
Marko

**Comment by aschempp** [comment]
Bestens. Bitte sag mir an welchen GitHub User oder Organisation ich das Repository übertragen soll. Ausserdem kannst du auf contao.org im ER einen Erweiterungstransfer beantragen (dazu brauchst du ein Konto): https://contao.org/de/extension-transfer.html

**Comment by markocupic** [comment]
Ok! Den Erweiterungstransfer habe ich beantragt.
Mein github Konto findest du hier:
https://github.com/markocupic
Liebe Grüsse
Marko

**Comment by aschempp** [comment]
Ich kann dir das Repository nicht zuweisen, sondern du musst dir das "holen". Nachdem du meine Einladung akzeptiert hast, kannst du das Repository in den Einstellungen selber transferieren.

**Comment by markocupic** [comment]
Ok. Kannst du mir sagen, wie ich das "holen" kann? 
Lg Marko

**Comment by aschempp** [comment]
https://help.github.com/articles/transferring-a-repository/

**Comment by markocupic** [comment]
Hoi Andi 
Es hat alles bestens geklappt. Das Modul ist nun contao 3.4 kompatibel und bei github nun unter https://github.com/markocupic/backend_password
zu finden. 
Ich danke dir für die Arbeit und deinen Aufwand.
E liebe Gruess
Marko

**Comment by aschempp** [comment]
hmm, warum gibt es denn jetzt zwei Repositories? Eigentlich sollte das hier weg sein…

**Comment by markocupic** [comment]
Vielleicht musst du es löschen.
Komisch...

**Comment by aschempp** [comment]
Naja, ich könnte es löschen. Aber das richtige wäre, dass du die Erweiterung von uns transferierst. Aktuell hast du sie einfach neu angelegt, womit beispielsweise alle Historie verloren geht.

**Comment by markocupic** [comment]
Wie sieht's jetzt aus?

**Comment by aschempp** [comment]
jetzt hast du einen Fork erstellt. Die Tatsache dass es in der Organisation "terminal42" das Repository noch gibt, sagt dass es nicht stimmt ;-)

Hast du meinen Link gelesen? https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts

**Comment by markocupic** [comment]
Ich habe den Link schon gesehen und auch gelesen.
Ich habe jetzt das repository nochmals gelöscht.
Den Fork habe nicht ich erstellt, der war schon da. Kannst du nochmals probieren deine Erweiterung zu transferieren?
Dann probier ichs nochmal.
Liebe Grüsse
Marko

**Comment by aschempp** [comment]
Ich kann nicht zu dir transferieren, das darfst nur du.

**Comment by markocupic** [comment]
Ich gehe davon aus, dass der Transfer vom Type Organization -> User ist.
Im How To steht dazu folgendes:
Users must have admin or owner access to a repository before they can transfer it out of the organization. If the user does not have this access, a temporary admin team can be created with only the user and repository in it. The user receiving the repository is the only one who can perform the transfer.
Im terminal42/contao-backend_password repository müsste ich auf die settings Zugriff haben. Habe ich aber nicht. Was mache ich falsch?
Liebe Grüsse
Marko

**Comment by aschempp** [comment]
jetzt scheint's geklappt zu haben ;-)
Ich hab dir ja eine Einladung geschickt damit du eben die Berechtigungen hast.

**Comment by markocupic** [comment]
Oh, Mann.
Jetzt hab ich's gesehen! Du hast mich eingeladen! Das musste ich zuerst bestätigen. Danach hatte ich auch Zugriff auf die Settings.
Sorry, dass ich mich so blöd angestellt habe. Aber ich habe wirklich nicht so oft damit zu tun.
Jetzt sollte es klappen. 
Liebe Grüsse
Marko

**Comment by markocupic** [comment]
Wieder etwas gelernt!
Ich danke dir.
Lg Marko

**Comment by aschempp** [comment]
Gern, danke dir! Jetzt musst du nur noch das Ticket schliessen, weil ich keine Rechte mehr hab :D

**Comment by markocupic** [comment]
Over and end ;-)
