### ISSUE TITLE
Password recovery link is added to FE login

### ISSUE THREAD

**Issue by hella-schu** [markocupic/backend_password#3]
If you have a FE login module and the member uses the wrong password, backend_password adds the same 'tl_message' to the FE login module. But this also leads to /contao/index.php?pwrecovery=1 like in the backend login module.
Is it possible to change that? I don't want to lead the FE-User to the BE-form.

**Comment by markocupic** [comment]
https://github.com/markocupic/backend_password/commit/abde2142d2896810c342e7484884fb9e85892139

**Comment by hella-schu** [comment]
Thank you very much for your quick action. Could you provide this version in packagist, please? Thanks!

**Comment by markocupic** [comment]
Hi Hella 
backend_password is on packagist now.
markocupic/backend_password
Kind regards
Marko

**Comment by hella-schu** [comment]
Thank you Marko!
