### ISSUE TITLE
Contao 3.5: Passwort-vergessen-Link ist falsch

### ISSUE THREAD

**Issue by Samson1964** [markocupic/backend_password#4]
Der Wert der Sprachvariablen $GLOBALS['TL_LANG']['ERR']['invalidLogin'] wird leider auch beim Frontend-Login eingeblendet, wenn man falsche Daten eingegeben hat. Und dort ist der Link zum Zurücksetzen des Backend-Passworts leider falsch, weil ja gar kein neues Backend-Passwort benötigt wird, sondern eins für das Frontend. .

**Comment by markocupic** [comment]
Hallo Frank
Alles klar! Probier mal mit der gefixten Version 3.0.1.
Liebe Grüsse
Marko

**Comment by Samson1964** [comment]
Super danke, Marko! 
Mir war dieses Problem noch nie aufgefallen. Erst gestern habe ich einen IT-erfahrenen Benutzer dabei beobachten können, wie er auf diesen Link geklick hat und ich plötzlich das Backend-Login sah. Jetzt verstehe ich auch manche Besucher meiner Seite, die mit "Passwort vergessen" nicht klarkamen.

**Comment by markocupic** [comment]
Ist mir auch nicht aufgefallen. Habe das Projekt damals von Terminal42 geerbt und für Contao3.5 fit gemacht. 
Danke dir!
Liebe Grüsse
Marko
